import { Inter } from 'next/font/google'
import './globals.css'
import { EmailJSResponseStatus } from 'emailjs-com'
import { env } from '../../next.config'
import emailjs from "@emailjs/browser"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
     
    </html>
  )
}
